


GET http://0.0.0.0:1338/users


### Error Controlado
GET http://0.0.0.0:1338/padawan



### 
POST http://0.0.0.0:1338/users/login
content-type: application/json

{
    "login": "juanin",
    "password": "jan Jarri"
}
// Verificar JWT en https://jwt.io/


GET http://0.0.0.0:1338/users



### 
POST http://0.0.0.0:1338/users
content-type: application/json

{
    "id": "3"
}

### 

PUT http://0.0.0.0:1338/users
content-type: application/json

{
    "id": "3",
    "name": "Manu",
    "lastname": "Ortega"
}




### 

DELETE  http://0.0.0.0:1338/users/1

